// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/algorithms/a-star" | "/algorithms/avl-delete" | "/algorithms/avl-insert" | "/algorithms/bellman-ford" | "/algorithms/bfs" | "/algorithms/binary-search" | "/algorithms/bst-delete" | "/algorithms/bst-insert" | "/algorithms/bst-search" | "/algorithms/bubble-sort" | "/algorithms/coin-change" | "/algorithms/counting-sort" | "/algorithms/dfs" | "/algorithms/dijkstra" | "/algorithms/dutch-flag" | "/algorithms/edit-distance" | "/algorithms/exponential-search" | "/algorithms/fibonacci" | "/algorithms/floyd-warshall" | "/algorithms/hash-table-operations" | "/algorithms/heap-extract" | "/algorithms/heap-insert" | "/algorithms/heap-sort" | "/algorithms/inorder-traversal" | "/algorithms/insertion-sort" | "/algorithms/interpolation-search" | "/algorithms/jump-search" | "/algorithms/kadane" | "/algorithms/kadane-algorithm" | "/algorithms/knapsack" | "/algorithms/knapsack-01" | "/algorithms/kruskal" | "/algorithms/lcs" | "/algorithms/level-order-traversal" | "/algorithms/linear-search" | "/algorithms/linked-list-delete" | "/algorithms/linked-list-insert" | "/algorithms/longest-common-subsequence" | "/algorithms/longest-increasing-subsequence" | "/algorithms/matrix-chain-multiplication" | "/algorithms/merge-sort" | "/algorithms/postorder-traversal" | "/algorithms/preorder-traversal" | "/algorithms/prim" | "/algorithms/queue" | "/algorithms/queue-enqueue-dequeue" | "/algorithms/quick-sort" | "/algorithms/radix-sort" | "/algorithms/selection-sort" | "/algorithms/sliding-window" | "/algorithms/stack" | "/algorithms/stack-push-pop" | "/algorithms/topological-sort" | "/algorithms/trie-insert" | "/algorithms/trie-operations" | "/algorithms/trie-search" | "/algorithms/two-pointers" | "/catalog"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/algorithms/a-star": {}
  "/algorithms/avl-delete": {}
  "/algorithms/avl-insert": {}
  "/algorithms/bellman-ford": {}
  "/algorithms/bfs": {}
  "/algorithms/binary-search": {}
  "/algorithms/bst-delete": {}
  "/algorithms/bst-insert": {}
  "/algorithms/bst-search": {}
  "/algorithms/bubble-sort": {}
  "/algorithms/coin-change": {}
  "/algorithms/counting-sort": {}
  "/algorithms/dfs": {}
  "/algorithms/dijkstra": {}
  "/algorithms/dutch-flag": {}
  "/algorithms/edit-distance": {}
  "/algorithms/exponential-search": {}
  "/algorithms/fibonacci": {}
  "/algorithms/floyd-warshall": {}
  "/algorithms/hash-table-operations": {}
  "/algorithms/heap-extract": {}
  "/algorithms/heap-insert": {}
  "/algorithms/heap-sort": {}
  "/algorithms/inorder-traversal": {}
  "/algorithms/insertion-sort": {}
  "/algorithms/interpolation-search": {}
  "/algorithms/jump-search": {}
  "/algorithms/kadane": {}
  "/algorithms/kadane-algorithm": {}
  "/algorithms/knapsack": {}
  "/algorithms/knapsack-01": {}
  "/algorithms/kruskal": {}
  "/algorithms/lcs": {}
  "/algorithms/level-order-traversal": {}
  "/algorithms/linear-search": {}
  "/algorithms/linked-list-delete": {}
  "/algorithms/linked-list-insert": {}
  "/algorithms/longest-common-subsequence": {}
  "/algorithms/longest-increasing-subsequence": {}
  "/algorithms/matrix-chain-multiplication": {}
  "/algorithms/merge-sort": {}
  "/algorithms/postorder-traversal": {}
  "/algorithms/preorder-traversal": {}
  "/algorithms/prim": {}
  "/algorithms/queue": {}
  "/algorithms/queue-enqueue-dequeue": {}
  "/algorithms/quick-sort": {}
  "/algorithms/radix-sort": {}
  "/algorithms/selection-sort": {}
  "/algorithms/sliding-window": {}
  "/algorithms/stack": {}
  "/algorithms/stack-push-pop": {}
  "/algorithms/topological-sort": {}
  "/algorithms/trie-insert": {}
  "/algorithms/trie-operations": {}
  "/algorithms/trie-search": {}
  "/algorithms/two-pointers": {}
  "/catalog": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
