// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/about/page.tsx
{
  const handler = {} as typeof import("../../src/app/about/page.js")
  handler satisfies AppPageConfig<"/about">
}

// Validate ../../src/app/algorithms/a-star/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/a-star/page.js")
  handler satisfies AppPageConfig<"/algorithms/a-star">
}

// Validate ../../src/app/algorithms/avl-delete/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/avl-delete/page.js")
  handler satisfies AppPageConfig<"/algorithms/avl-delete">
}

// Validate ../../src/app/algorithms/avl-insert/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/avl-insert/page.js")
  handler satisfies AppPageConfig<"/algorithms/avl-insert">
}

// Validate ../../src/app/algorithms/bellman-ford/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/bellman-ford/page.js")
  handler satisfies AppPageConfig<"/algorithms/bellman-ford">
}

// Validate ../../src/app/algorithms/bfs/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/bfs/page.js")
  handler satisfies AppPageConfig<"/algorithms/bfs">
}

// Validate ../../src/app/algorithms/binary-search/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/binary-search/page.js")
  handler satisfies AppPageConfig<"/algorithms/binary-search">
}

// Validate ../../src/app/algorithms/bst-delete/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/bst-delete/page.js")
  handler satisfies AppPageConfig<"/algorithms/bst-delete">
}

// Validate ../../src/app/algorithms/bst-insert/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/bst-insert/page.js")
  handler satisfies AppPageConfig<"/algorithms/bst-insert">
}

// Validate ../../src/app/algorithms/bst-search/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/bst-search/page.js")
  handler satisfies AppPageConfig<"/algorithms/bst-search">
}

// Validate ../../src/app/algorithms/bubble-sort/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/bubble-sort/page.js")
  handler satisfies AppPageConfig<"/algorithms/bubble-sort">
}

// Validate ../../src/app/algorithms/coin-change/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/coin-change/page.js")
  handler satisfies AppPageConfig<"/algorithms/coin-change">
}

// Validate ../../src/app/algorithms/counting-sort/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/counting-sort/page.js")
  handler satisfies AppPageConfig<"/algorithms/counting-sort">
}

// Validate ../../src/app/algorithms/dfs/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/dfs/page.js")
  handler satisfies AppPageConfig<"/algorithms/dfs">
}

// Validate ../../src/app/algorithms/dijkstra/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/dijkstra/page.js")
  handler satisfies AppPageConfig<"/algorithms/dijkstra">
}

// Validate ../../src/app/algorithms/dutch-flag/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/dutch-flag/page.js")
  handler satisfies AppPageConfig<"/algorithms/dutch-flag">
}

// Validate ../../src/app/algorithms/edit-distance/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/edit-distance/page.js")
  handler satisfies AppPageConfig<"/algorithms/edit-distance">
}

// Validate ../../src/app/algorithms/exponential-search/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/exponential-search/page.js")
  handler satisfies AppPageConfig<"/algorithms/exponential-search">
}

// Validate ../../src/app/algorithms/fibonacci/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/fibonacci/page.js")
  handler satisfies AppPageConfig<"/algorithms/fibonacci">
}

// Validate ../../src/app/algorithms/floyd-warshall/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/floyd-warshall/page.js")
  handler satisfies AppPageConfig<"/algorithms/floyd-warshall">
}

// Validate ../../src/app/algorithms/hash-table-operations/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/hash-table-operations/page.js")
  handler satisfies AppPageConfig<"/algorithms/hash-table-operations">
}

// Validate ../../src/app/algorithms/heap-extract/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/heap-extract/page.js")
  handler satisfies AppPageConfig<"/algorithms/heap-extract">
}

// Validate ../../src/app/algorithms/heap-insert/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/heap-insert/page.js")
  handler satisfies AppPageConfig<"/algorithms/heap-insert">
}

// Validate ../../src/app/algorithms/heap-sort/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/heap-sort/page.js")
  handler satisfies AppPageConfig<"/algorithms/heap-sort">
}

// Validate ../../src/app/algorithms/inorder-traversal/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/inorder-traversal/page.js")
  handler satisfies AppPageConfig<"/algorithms/inorder-traversal">
}

// Validate ../../src/app/algorithms/insertion-sort/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/insertion-sort/page.js")
  handler satisfies AppPageConfig<"/algorithms/insertion-sort">
}

// Validate ../../src/app/algorithms/interpolation-search/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/interpolation-search/page.js")
  handler satisfies AppPageConfig<"/algorithms/interpolation-search">
}

// Validate ../../src/app/algorithms/jump-search/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/jump-search/page.js")
  handler satisfies AppPageConfig<"/algorithms/jump-search">
}

// Validate ../../src/app/algorithms/kadane-algorithm/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/kadane-algorithm/page.js")
  handler satisfies AppPageConfig<"/algorithms/kadane-algorithm">
}

// Validate ../../src/app/algorithms/kadane/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/kadane/page.js")
  handler satisfies AppPageConfig<"/algorithms/kadane">
}

// Validate ../../src/app/algorithms/knapsack-01/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/knapsack-01/page.js")
  handler satisfies AppPageConfig<"/algorithms/knapsack-01">
}

// Validate ../../src/app/algorithms/knapsack/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/knapsack/page.js")
  handler satisfies AppPageConfig<"/algorithms/knapsack">
}

// Validate ../../src/app/algorithms/kruskal/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/kruskal/page.js")
  handler satisfies AppPageConfig<"/algorithms/kruskal">
}

// Validate ../../src/app/algorithms/lcs/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/lcs/page.js")
  handler satisfies AppPageConfig<"/algorithms/lcs">
}

// Validate ../../src/app/algorithms/level-order-traversal/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/level-order-traversal/page.js")
  handler satisfies AppPageConfig<"/algorithms/level-order-traversal">
}

// Validate ../../src/app/algorithms/linear-search/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/linear-search/page.js")
  handler satisfies AppPageConfig<"/algorithms/linear-search">
}

// Validate ../../src/app/algorithms/linked-list-delete/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/linked-list-delete/page.js")
  handler satisfies AppPageConfig<"/algorithms/linked-list-delete">
}

// Validate ../../src/app/algorithms/linked-list-insert/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/linked-list-insert/page.js")
  handler satisfies AppPageConfig<"/algorithms/linked-list-insert">
}

// Validate ../../src/app/algorithms/longest-common-subsequence/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/longest-common-subsequence/page.js")
  handler satisfies AppPageConfig<"/algorithms/longest-common-subsequence">
}

// Validate ../../src/app/algorithms/longest-increasing-subsequence/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/longest-increasing-subsequence/page.js")
  handler satisfies AppPageConfig<"/algorithms/longest-increasing-subsequence">
}

// Validate ../../src/app/algorithms/matrix-chain-multiplication/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/matrix-chain-multiplication/page.js")
  handler satisfies AppPageConfig<"/algorithms/matrix-chain-multiplication">
}

// Validate ../../src/app/algorithms/merge-sort/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/merge-sort/page.js")
  handler satisfies AppPageConfig<"/algorithms/merge-sort">
}

// Validate ../../src/app/algorithms/postorder-traversal/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/postorder-traversal/page.js")
  handler satisfies AppPageConfig<"/algorithms/postorder-traversal">
}

// Validate ../../src/app/algorithms/preorder-traversal/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/preorder-traversal/page.js")
  handler satisfies AppPageConfig<"/algorithms/preorder-traversal">
}

// Validate ../../src/app/algorithms/prim/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/prim/page.js")
  handler satisfies AppPageConfig<"/algorithms/prim">
}

// Validate ../../src/app/algorithms/queue-enqueue-dequeue/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/queue-enqueue-dequeue/page.js")
  handler satisfies AppPageConfig<"/algorithms/queue-enqueue-dequeue">
}

// Validate ../../src/app/algorithms/queue/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/queue/page.js")
  handler satisfies AppPageConfig<"/algorithms/queue">
}

// Validate ../../src/app/algorithms/quick-sort/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/quick-sort/page.js")
  handler satisfies AppPageConfig<"/algorithms/quick-sort">
}

// Validate ../../src/app/algorithms/radix-sort/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/radix-sort/page.js")
  handler satisfies AppPageConfig<"/algorithms/radix-sort">
}

// Validate ../../src/app/algorithms/selection-sort/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/selection-sort/page.js")
  handler satisfies AppPageConfig<"/algorithms/selection-sort">
}

// Validate ../../src/app/algorithms/sliding-window/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/sliding-window/page.js")
  handler satisfies AppPageConfig<"/algorithms/sliding-window">
}

// Validate ../../src/app/algorithms/stack-push-pop/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/stack-push-pop/page.js")
  handler satisfies AppPageConfig<"/algorithms/stack-push-pop">
}

// Validate ../../src/app/algorithms/stack/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/stack/page.js")
  handler satisfies AppPageConfig<"/algorithms/stack">
}

// Validate ../../src/app/algorithms/topological-sort/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/topological-sort/page.js")
  handler satisfies AppPageConfig<"/algorithms/topological-sort">
}

// Validate ../../src/app/algorithms/trie-insert/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/trie-insert/page.js")
  handler satisfies AppPageConfig<"/algorithms/trie-insert">
}

// Validate ../../src/app/algorithms/trie-operations/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/trie-operations/page.js")
  handler satisfies AppPageConfig<"/algorithms/trie-operations">
}

// Validate ../../src/app/algorithms/trie-search/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/trie-search/page.js")
  handler satisfies AppPageConfig<"/algorithms/trie-search">
}

// Validate ../../src/app/algorithms/two-pointers/page.tsx
{
  const handler = {} as typeof import("../../src/app/algorithms/two-pointers/page.js")
  handler satisfies AppPageConfig<"/algorithms/two-pointers">
}

// Validate ../../src/app/catalog/page.tsx
{
  const handler = {} as typeof import("../../src/app/catalog/page.js")
  handler satisfies AppPageConfig<"/catalog">
}

// Validate ../../src/app/page.tsx
{
  const handler = {} as typeof import("../../src/app/page.js")
  handler satisfies AppPageConfig<"/">
}







// Validate ../../src/app/layout.tsx
{
  const handler = {} as typeof import("../../src/app/layout.js")
  handler satisfies LayoutConfig<"/">
}
